/**
 * Shared Tailwind theme — the single source of truth replacing tokens.ts,
 * consumed as a `presets: [...]` entry by both apps/web's tailwind.config.ts
 * (shadcn/Radix) and apps/mobile's tailwind.config.js (NativeWind). Plain
 * CommonJS, not TSX like the rest of this package: Tailwind's and
 * NativeWind's config loaders `require()` this directly at build time,
 * outside of Metro/webpack's own transform pipeline, so it must run as-is
 * under plain Node rather than depend on a bundler transform.
 *
 * No CSS-variable/dark-mode indirection (the usual shadcn `hsl(var(--x))`
 * pattern) — this app has no dark mode requirement today, so colors are
 * plain hex, same philosophy as the tokens.ts file this replaces ("plain
 * data, no platform split needed").
 *
 * Two families of keys:
 *  - The app's own brand tokens (primary, textMuted, dangerBg, star, ...),
 *    carried over 1:1 from tokens.ts so existing mental models transfer.
 *  - shadcn's expected semantic slot names (background, foreground, card,
 *    popover, primary/secondary/destructive/muted/accent + their
 *    "-foreground" pairs, border, input, ring) so components generated by
 *    `shadcn add` render on-brand without per-component edits. Mapped from
 *    the closest existing tokens.ts value/Button.tsx variant color — see
 *    inline comments; exact nuance (e.g. Button's outline-style "danger"
 *    variant vs shadcn's solid "destructive") gets refined per-component as
 *    each one is actually rebuilt with cva, not required to be pixel-exact
 *    here.
 */
module.exports = {
  theme: {
    extend: {
      colors: {
        // ---- brand tokens (1:1 from tokens.ts) ----
        // Object form (not a plain string) so `text-primary-foreground`
        // resolves too — needed by shadcn-generated components' default
        // `bg-primary text-primary-foreground` className pairing.
        primary: { DEFAULT: "#0F766E", foreground: "#FFFFFF" },
        primaryDark: "#0B564F",
        primaryLight: "#CCFBF1",
        surface: "#FFFFFF",
        text: "#1C1917",
        textBody: "#292524",
        textMuted: "#78716C",
        // Secondary/inactive nav-adjacent gray — sits between textBody and
        // textMuted. Found hardcoded as "#57534E" in apps/web (HeaderBar's
        // inactive nav links/locale toggle, ExploreView's Open Now button)
        // during the apps/web Tailwind conversion; promoted to a token since
        // it's a real recurring role, not a one-off.
        textSecondary: "#57534E",
        textFaint: "#A8A29E",
        textOnPrimary: "#FFFFFF",
        danger: "#DC2626",
        dangerDark: "#B91C1C",
        dangerLight: "#FEE2E2",
        dangerBg: "#FEF2F2",
        dangerBorder: "#FECACA",
        success: "#15803D",
        warning: "#D97706",
        star: "#F59E0B",
        starEmpty: "#E7E2D8",
        divider: "#EDE7DC",
        tealTint: "#F0FDF9",

        // ---- shadcn semantic slots ----
        background: "#FFFBF5",
        foreground: "#1C1917",
        border: "#E7E2D8",
        input: "#E7E2D8",
        ring: "#0F766E",
        card: { DEFAULT: "#FFFFFF", foreground: "#1C1917" },
        popover: { DEFAULT: "#FFFFFF", foreground: "#1C1917" },
        // Matches Button.tsx's secondary variant (primaryLight bg / primaryDark text).
        secondary: { DEFAULT: "#CCFBF1", foreground: "#0B564F" },
        // shadcn's destructive is solid-filled — our Button's own "danger"
        // variant is an outline treatment instead (dangerBg/dangerDark/
        // dangerBorder); this slot intentionally uses the solid `danger` red.
        destructive: { DEFAULT: "#DC2626", foreground: "#FFFFFF" },
        // No separate "muted background" token exists in tokens.ts — reuses
        // `background`, which is already a light neutral distinct from `surface`.
        muted: { DEFAULT: "#FFFBF5", foreground: "#78716C" },
        // Matches tealTint's existing use as a selected-row tint.
        accent: { DEFAULT: "#F0FDF9", foreground: "#0B564F" },
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        "2xl": "32px",
        "3xl": "48px",
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        input: "14px",
        lg: "16px",
        xl: "24px",
        cardLg: "20px",
        pill: "9999px",
      },
      // fontSizes + letterSpacings from tokens.ts collapsed into Tailwind's
      // [size, { letterSpacing }] tuple form.
      fontSize: {
        xs: ["12px", { letterSpacing: "1.3px" }],
        sm: ["14px", { letterSpacing: "0px" }],
        md: ["16px", { letterSpacing: "0px" }],
        lg: ["18px", { letterSpacing: "-0.1px" }],
        xl: ["22px", { letterSpacing: "-0.3px" }],
        "2xl": ["28px", { letterSpacing: "-0.5px" }],
        "3xl": ["34px", { letterSpacing: "-0.7px" }],
      },
      // fontWeights' custom regular/medium/semibold/bold names are dropped —
      // they're already Tailwind's built-in font-normal/medium/semibold/bold
      // (400/500/600/700), no custom key needed.
      boxShadow: {
        card: "0 1px 3px rgba(28, 25, 23, 0.08), 0 1px 2px rgba(28, 25, 23, 0.06)",
        elevated: "0 8px 24px rgba(28, 25, 23, 0.16)",
        // Button's primary-variant teal glow and IconButton's solid-variant
        // lift — web-only shadow values (native equivalents are the separate
        // nativeShadows.buttonGlow/iconSolid RN shadow-prop objects, see
        // native-shadows.ts) carried over unchanged from Button.tsx/
        // IconButton.tsx's previous inline boxShadow strings.
        buttonGlow: "0 4px 14px rgba(15, 118, 110, 0.28)",
        iconSolid: "0 1px 4px rgba(28, 25, 23, 0.15)",
        // The actual dominant "content panel" shadow in apps/web — found
        // hardcoded verbatim in 10+ files (list rows, form cards, the auth
        // card) during the apps/web Tailwind conversion, more often than
        // `card`/`elevated` above. Distinct two-layer shadow, not a rounding
        // of either existing token.
        panel: "0 1px 3px rgba(28, 25, 23, 0.08), 0 6px 18px rgba(28, 25, 23, 0.05)",
      },
      // Matches apps/web's existing hand-written breakpoints (globals.css) —
      // retired class-by-class in Phase 4/6 as components move to these.
      screens: {
        admin: "768px",
        explore: "860px",
        header: "900px",
      },
    },
  },
};
